In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [ ]:
df = pd.read_csv("CrimeData3.csv")
print(df.head())

                                     id                type  \
0  5d912794-6a5b-11ed-96df-00155dee685c  theft from vehicle   
1  5d91492c-6a5b-11ed-96df-00155dee685c  theft from vehicle   
2  5d9153ae-6a5b-11ed-96df-00155dee685c  theft from vehicle   
3  5d915c8c-6a5b-11ed-96df-00155dee685c  theft from vehicle   
4  5d91663c-6a5b-11ed-96df-00155dee685c  theft from vehicle   

                       timestamp  year  month  day  hour  minute  \
0  2003-02-05T23:00:00.000-08:00  2003      2    5    23       0   
1  2015-11-05T05:57:00.000-08:00  2015     11    5     5      57   
2  2004-09-26T18:00:00.000-07:00  2004      9   26    18       0   
3  2010-12-15T08:00:00.000-08:00  2010     12   15     8       0   
4  2016-06-03T14:30:00.000-07:00  2016      6    3    14      30   

               neighbourhood  x_neighbourhood  y_neighbourhood hundred_block  \
0                    marpole         49.25430       -123.13563    w 71st ave   
1                   fairview         49.24621       

In [ ]:
df = df[['year','month','day','hour','minute','hundred_block', 'x_neighbourhood', 'y_neighbourhood','x','y','type', 'neighbourhood']]
print(df['type'].nunique())

9


In [ ]:
df = df[['year','month','day','hour','minute','hundred_block', 'x_neighbourhood', 'y_neighbourhood', 'x','y','type', 'neighbourhood']]
crime_df = df.rename(columns = {"type": "target"})
crime_df['target'] = crime_df['target'].astype('string')
crime_df['neighbourhood'] = crime_df['neighbourhood'].astype('string')
crime_df['hundred_block'] = crime_df['hundred_block'].astype('string')

crime_df = crime_df.loc[(crime_df['hundred_block']!='NaN')]
crime_df = crime_df.loc[(crime_df['hundred_block']!='NaN')]
crime_df = crime_df.loc[(crime_df['target']!='theft of vehicle')]
# crime_df = crime_df.loc[(crime_df['target']!='other theft')]
crime_df = crime_df.loc[(crime_df['target']!='theft of bicycle')]
crime_df = crime_df.loc[(crime_df['target']!='vehicle collision or pedestrian struck (with injury)')]
crime_df = crime_df.loc[(crime_df['target']!='vehicle collision or pedestrian struck (with fatality)')]
crime_df = crime_df.loc[(crime_df['target']!='break and enter commercial')]
crime_df = crime_df.loc[(crime_df['target']!='break and enter residential/other')]
crime_df = crime_df.loc[(crime_df['x']!=0)]
crime_df = crime_df.loc[(crime_df['y']!=0)]
print(crime_df)
crime_df['target'].value_counts()

        year  month  day  hour  minute hundred_block  x_neighbourhood  \
0       2003      2    5    23       0    w 71st ave         49.25430   
1       2015     11    5     5      57     w 7th ave         49.24621   
2       2004      9   26    18       0  w cordova st         49.27759   
3       2010     12   15     8       0  w georgia st         49.27759   
4       2016      6    3    14      30  w georgia st         49.26333   
...      ...    ...  ...   ...     ...           ...              ...   
364200  2008      7    3    10      37     nk_loc st         49.24744   
364201  2012      5   27    16       0     nk_loc st         49.24744   
364202  2014      7    7     4       0     nk_loc st         49.24744   
364203  2014      9   10    16       0     nk_loc st         49.24744   
364204  2021      6   26    19       0     nk_loc st         49.24744   

        y_neighbourhood          x          y              target  \
0            -123.13563  49.207012 -123.13401  theft f

theft from vehicle    113776
other theft            90118
mischief               49414
Name: target, dtype: Int64

In [ ]:
crime_df.info()
crime_df['target'].value_counts()
# crime_df.loc[(0 <= df['hour']) & (df['hour'] <= 6),"hour"] = 0
# crime_df.loc[(7 <= df['hour']) & (df['hour'] <= 12),"hour"] = 1
# crime_df.loc[(13 <= df['hour']) & (df['hour'] <= 18),"hour"] = 2
# crime_df.loc[(19 <= df['hour']) & (df['hour'] <= 23),"hour"] = 3

<class 'pandas.core.frame.DataFrame'>
Int64Index: 253308 entries, 0 to 364204
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   year             253308 non-null  int64  
 1   month            253308 non-null  int64  
 2   day              253308 non-null  int64  
 3   hour             253308 non-null  int64  
 4   minute           253308 non-null  int64  
 5   hundred_block    253308 non-null  string 
 6   x_neighbourhood  253308 non-null  float64
 7   y_neighbourhood  253308 non-null  float64
 8   x                253308 non-null  float64
 9   y                253308 non-null  float64
 10  target           253308 non-null  string 
 11  neighbourhood    253308 non-null  string 
dtypes: float64(4), int64(5), string(3)
memory usage: 25.1 MB


theft from vehicle    113776
other theft            90118
mischief               49414
Name: target, dtype: Int64

In [ ]:
print((crime_df['x']==0).any())
print((crime_df['y']==0).any())

False
False


In [ ]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y_le = crime_df['target']
crime_df['target'] = labelencoder.fit_transform(crime_df['target'])
label_map = dict(zip(y_le, crime_df['target']))
print(label_map)


y_le2 = crime_df['neighbourhood']
crime_df['neighbourhood'] = labelencoder.fit_transform(crime_df['neighbourhood'])
label_map2 = dict(zip(y_le2, crime_df['neighbourhood']))
print(label_map2)


y_le3 = crime_df['hundred_block']
crime_df['hundred_block'] = labelencoder.fit_transform(crime_df['hundred_block'])
label_map3 = dict(zip(y_le3, crime_df['hundred_block']))
print(label_map3)

# print(crime_df['TARGET'].value_counts())
#label_map = dict(zip(crime_df['HUNDRED_BLOCK'], y_le))
# crime_df['HUNDRED_BLOCK'] = labelencoder.fit_transform(crime_df['HUNDRED_BLOCK'])
# crime_df['NEIGHBOURHOOD'] = labelencoder.fit_transform(crime_df['NEIGHBOURHOOD'])
crime_df.head(5)


with open('target_label.pkl', 'wb') as files:
    pickle.dump(label_map, files)
  
with open('neighbourhood_label.pkl', 'wb') as files:
    pickle.dump(label_map2, files)

with open('hundred_block_label.pkl', 'wb') as files:
    pickle.dump(label_map3, files)


{'theft from vehicle': 2, 'mischief': 0, 'other theft': 1}
{'marpole': 10, 'fairview': 3, 'central business district': 1, 'west end': 22, 'hastings-sunrise': 5, 'west point grey': 23, 'mount pleasant': 11, 'kensington-cedar cottage': 6, 'sunset': 20, 'shaughnessy': 16, 'oakridge': 13, 'kitsilano': 9, 'grandview-woodland': 4, 'strathcona': 19, 'victoria-fraserview': 21, 'stanley park': 18, 'kerrisdale': 7, 'riley park': 15, 'arbutus ridge': 0, 'renfrew-collingwood': 14, 'killarney': 8, 'dunbar-southlands': 2, 'south cambie': 17, 'musqueam': 12}
{'w 71st ave': 1118, 'w 7th ave': 1124, 'w cordova st': 1130, 'w georgia st': 1131, 'w hastings st': 1132, 'alberni st': 85, 'barclay st': 139, 'boundary rd': 182, 'burnaby st': 203, 'cartwright st': 230, 'discovery st': 329, 'e 15th ave': 355, 'e 26th ave': 367, 'e 29th ave': 370, 'e 64th ave': 409, 'e kent n ave': 423, 'haro st': 531, 'howe st': 559, 'johnston st': 592, 'pacific blvd': 810, 'pendrell st': 823, 'quebec st': 857, 'robson st': 886

In [ ]:
crime_df['time'] = crime_df['hour'] + (crime_df['minute']/60)
crime_df.head()
print(crime_df['neighbourhood'].nunique())
print(crime_df['hundred_block'].nunique())

24
1197


In [ ]:
X = crime_df[['year','month','hour','neighbourhood','hundred_block']]
y = crime_df['target']
print(X.head(5))
print(y.head(5))

   year  month  hour  neighbourhood  hundred_block
0  2003      2    23             10           1118
1  2015     11     5              3           1124
2  2004      9    18              1           1130
3  2010     12     8              1           1131
4  2016      6    14             22           1131
0    2
1    2
2    2
3    2
4    2
Name: target, dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# **KNN Implementation**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25)

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

[[ 1810  4663  9798]
 [ 1367 18999  9513]
 [ 1898  8586 26958]]
              precision    recall  f1-score   support

           0       0.36      0.11      0.17     16271
           1       0.59      0.64      0.61     29879
           2       0.58      0.72      0.64     37442

    accuracy                           0.57     83592
   macro avg       0.51      0.49      0.48     83592
weighted avg       0.54      0.57      0.54     83592



In [ ]:
print(set(y_test) - set(y_pred))
print(knn.score(X_test, y_test))

In [ ]:
with open('KNNmodel.pkl', 'wb') as files:
    pickle.dump(knn, files)
    

In [ ]:
pickled_model = pickle.load(open('model.pkl', 'rb'))
pickled_target_label = pickle.load(open('target_label.pkl', 'rb'))
pickled_neighbourhood_label = pickle.load(open('neighbourhood_label.pkl', 'rb'))
pickled_hundred_block_label = pickle.load(open('hundred_block_label.pkl', 'rb'))

In [ ]:
predicted_label = pickled_model.predict([[2019, 10, 23, pickled_neighbourhood_label['hastings-sunrise'], pickled_hundred_block_label['windermere st']]])

key = [k for k, v in label_map.items() if v == predicted_label]
print(key)


['theft from vehicle']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


# **Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfm = RandomForestClassifier(n_estimators = 10)
rfm.fit(X_train, y_train)

RandomForestClassifier(n_estimators=10)

In [ ]:
y_pred = rfm.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

[[ 3773  4551  7947]
 [ 3861 16752  9266]
 [ 5860  8892 22690]]
              precision    recall  f1-score   support

           0       0.28      0.23      0.25     16271
           1       0.55      0.56      0.56     29879
           2       0.57      0.61      0.59     37442

    accuracy                           0.52     83592
   macro avg       0.47      0.47      0.47     83592
weighted avg       0.51      0.52      0.51     83592



In [ ]:
rfm.score(X_test,y_test)

0.5169753086419753